name: Build Dev

on:
  push:
   branches:
     - dev
      
permissions: write-all

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          make build
          mv ./bin/teldrive ./teldrive

      - name: Set Vars
        run: |
         echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: goreleaser.dockerfile
          push: true
          tags: ${{ env.IMAGE }}:dev